[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev"]
cacheDirectories = ["node_modules"]

[phases.build]
cmds = ["rm -rf dist && npm run build"]

[start]
cmd = "npm start"
