[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev"]
cacheDirectories = ["node_modules"]

[phases.build]
cmds = ["npm run build"]
cacheDirectories = ["dist"]

[start]
cmd = "npm start"
